# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Conda Third Party Tests

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  tests:
    name: "Conda"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda update -q conda
          $CONDA/bin/conda install conda-build=3.21.0

          $CONDA/bin/conda config --add channels conda-forge
          $CONDA/bin/conda config --add channels domdfcoding

      - name: Build sphinx-toolbox
        run: |
          git clone https://github.com/sphinx-toolbox/sphinx-toolbox
          STDOUT=$(python3 tests/make_package.py sphinx-toolbox)
          printf "$STDOUT\n"
          FILENAME=$(printf "$STDOUT" | tail -n 1)
          echo $FILENAME

          $CONDA/bin/conda index ./sphinx-toolbox/conda-bld || exit 1
          $CONDA/bin/conda install -c file://$(pwd)/sphinx-toolbox/conda-bld sphinx-toolbox=2.12.0 -y || exit 1
          $CONDA/bin/python -c "import sphinx_toolbox" || exit 1
          $CONDA/bin/pip install -r sphinx-toolbox/tests/requirements.txt || exit 1
          $CONDA/bin/pytest sphinx-toolbox/tests || exit 1
