# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Conda Third Party Tests

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  tests:
    name: "Conda"
    runs-on: ubuntu-latest

    strategy:
        fail-fast: False
        matrix:
          config:
            - {repo: "sphinx-toolbox/sphinx-toolbox", name: "sphinx-toolbox", version: "2.12.0"}
            - {repo: "sphinx-toolbox/default-values", name: "default_values", version: "0.4.3"}
            - {repo: "repo-helper/whey", name: "whey", version: "0.0.14"}
            - {repo: "domdfcoding/consolekit", name: "consolekit", version: "1.2.2 "}
            - {repo: "domdfcoding/mathematical", name: "mathematical", version: "0.5.0"}

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda update -q conda
          $CONDA/bin/conda install conda-build=3.21.0

          $CONDA/bin/conda config --add channels conda-forge
          $CONDA/bin/conda config --add channels domdfcoding

      - name: "Build ${{ matrix.config.name }}"
        run: |
          git clone https://github.com/${{ matrix.config.repo }} ${{ matrix.config.name }}
          python3 tests/make_package.py ${{ matrix.config.name }}

          $CONDA/bin/conda index ./${{ matrix.config.name }}/conda-bld || exit 1
          $CONDA/bin/conda install -c file://$(pwd)/${{ matrix.config.name }}/conda-bld ${{ matrix.config.name }}=${{ matrix.config.version }} -y || exit 1
          $CONDA/bin/pip install -r ${{ matrix.config.name }}/tests/requirements.txt || exit 1
          $CONDA/bin/pytest ${{ matrix.config.name }}/tests || exit 1
